import IdBase from '../idbase.a.ts';
import GuildPayload, { GuildFeatures } from '../base/guild.ts';

export default class Guild extends IdBase implements GuildPayload {
  declare readonly id;
  name;
  icon?;
  icon_hash?;
  splash?;
  discovery_splash?;
  owner?;
  readonly owner_id;
  permissions?;
  region?;
  afk_channel_id?;
  afk_timeout;
  widget_enabled?;
  widget_channel_id?;
  verification_level;
  default_message_notifications;
  explicit_content_filter;
  roles;
  emojis;
  features;
  mfa_level;
  application_id?;
  system_channel_id?;
  system_channel_flags;
  rules_channel_id?;
  joined_at?;
  large?;
  unavailable?;
  member_count?;
  voice_states?;
  members?;
  channels?;
  threads?;
  presences?;
  max_presences?;
  max_members?;
  vanity_url_code?;
  description?;
  banner?;
  premium_tier;
  premium_subscription_count?;
  preferred_locale;
  public_updates_channel_id?;
  max_video_channel_users?;
  approximate_member_count?;
  approximate_presence_count?;
  welcome_screen?;
  nsfw_level?;
  stage_instances?;
  stickers?;
  guild_scheduled_events?;
  premium_progress_bar_enabled;
}